version: '3.2'

services:
  web:
    # image: httpd:2.4
    build:
      context: ./docker
      dockerfile: web.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/local/apache2/htdocs